baseURL = 'http://go-curious.dev/'
languageCode = 'en-us'
title = 'Go Curious'
theme = 'ananke'

[params]
    background_color_class = 'bg-light-blue'
    text_color = ''


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoCuriousDev"

[[params.ananke_socials]]
name = "mastodon"
url = "https://social.example.com/@username"
rel = "me noopener"